### ISSUE TITLE
FYI for Windows users, change EOL characters

### ISSUE THREAD

**Issue by kuhlaid** [delboy1978uk/lamp#16]
In Windows OS using WSL, to run the bash commands like `bin/start` those scripts need to be LF end of line characters. The problem is that Windows will clone the GitHub repository code as CRLF line ending (which is a pain to resolve without a script). I use `find . -type f -print0 | xargs -0 dos2unix -ic0 | xargs -0 dos2unix -b` to automatically switch the EOL characters to LF.

**Comment by delboy1978uk** [comment]
You should fix your Git config to always use LF. See here! https://stackoverflow.com/a/13154031/3732075

**Comment by kuhlaid** [comment]
Thank you @delboy1978uk . I needed to stop using VSCode built-in Git cloning option and clone repositories using `git clone --config core.autocrlf=false [repo path]` instead.

**Comment by delboy1978uk** [comment]
@kuhlaid you should be able to run `git config --global core.autocrlf false` to apply it to all new repositories. For existing repositories, you might need to cd into the folder and say `git config core.autocrlf false` without the global flag.
If this doesn't fix your VSCode, then it will be using a different git executable. find it, and run the global setting on  that too! Have a great day :-D
